# Build configuration for debugging
---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y -DCONFIG_ZMK_LOG_LEVEL_DBG=y
    artifact-name: corne_left_debug
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_right