# Build configuration for debugging
---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: zmk-usb-logging zmk-studio
    artifact-name: corne_left_debug

  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_right
